services:
  # Frontend Service (Static Site)
  - type: web
    name: disaster-management-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://disaster-management-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Service (Node.js API)
  - type: web
    name: disaster-management-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
